### ISSUE TITLE
Can you publish the latest version 4.1.4 to dockerhub

### ISSUE THREAD

**Issue by sajiljosephs** [powa-team/powa-web#169]
Can you publish the latest version 4.1.4 to dockerhub

**Comment by rjuju** [comment]
Oh sorry I totally forgot to do that.  Images are currently being rebuilt and pushed, the powa-archivist for pg10 is already available and the rest will be uploaded as versions are rebuilt.

Note that images are now based on debian 11 (bullseye).

**Comment by sajiljosephs** [comment]
Powa-web is on 4.1.3 version with docker, need the latest 4.1.4

**Comment by rjuju** [comment]
All the images just finished building and uploading, including the last powa-web version.

Sorry it took a bit more time than expected, I had to fix build random failures along the way due to changes with the upstream postgres packages.

**Comment by sajiljosephs** [comment]
No problem. Thanks

**Comment by sajiljosephs** [comment]
The images doesnt seems to work. Error below:

==
Traceback (most recent call last):
  File "/usr/local/bin/powa-web", line 4, in <module>
    from powa import make_app
  File "/usr/local/lib/python3.9/dist-packages/powa/__init__.py", line 21, in <module>
    from powa.overview import Overview
  File "/usr/local/lib/python3.9/dist-packages/powa/overview.py", line 12, in <module>
    from powa.server import ServerOverview
  File "/usr/local/lib/python3.9/dist-packages/powa/server.py", line 15, in <module>
    from powa.config import ConfigChangesGlobal
  File "/usr/local/lib/python3.9/dist-packages/powa/config.py", line 9, in <module>
    from powa.sql.views import get_config_changes
  File "/usr/local/lib/python3.9/dist-packages/powa/sql/views.py", line 5, in <module>
    from powa.sql.utils import diff
  File "/usr/local/lib/python3.9/dist-packages/powa/sql/utils.py", line 7, in <module>
    block_size = select([cast(func.current_setting('block_size'), Numeric)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/_selectable_constructors.py", line 489, in select
    return Select(*entities)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/selectable.py", line 5132, in __init__
    self._raw_columns = [
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/selectable.py", line 5133, in <listcomp>
    coercions.expect(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/coercions.py", line 652, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/coercions.py", line 1143, in _raise_for_expected
    return super()._raise_for_expected(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/coercions.py", line 711, in _raise_for_expected
    super()._raise_for_expected(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/coercions.py", line 536, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [<sqlalchemy.sql.elements.Label at 0x7f152dffa910; block_size>]. Did you mean to say select(<sqlalchemy.sql.elements.Label at 0x7f152dffa910; block_size>)?
==

**Comment by rjuju** [comment]
Ah, apparently sqlalchemy broke their API again in version 2.0.  I pushed a new version relying on sqlalchemy 1.4.  I entirely removed all sqlalchemy usage in the next version of powa-web (5) so hopefully this kind of problem shouldn't happen again.

**Comment by sajiljosephs** [comment]
Perfect. Its working now. Thanks.

**Comment by rjuju** [comment]
Great, thanks for the confirmation!
