### ISSUE TITLE
"Index Suggestions" errors when hypopg is not installed

### ISSUE THREAD

**Issue by pgiraud** [powa-team/powa-web#243]
In the query overview, if hypopg is not installed for the given database, the "Index Suggestions" in "Predicates" tab loads indefinitely . The corresponding XHR request actually returns a 500 error:

/server/1/metrics/database/obvious/query/9191891907659356179/indexes/?from=2024-12-20%2008%3A28%3A07%2B0100&to=2024-12-20%2009%3A28%3A07%2B0100
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1711, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/src/powa-web-dev/powa/query.py", line 583, in get
    ind.name = self.execute(
  File "/usr/local/src/powa-web-dev/powa/framework.py", line 653, in execute
    raise e
  File "/usr/local/src/powa-web-dev/powa/framework.py", line 641, in execute
    cur.execute(query, params)
  File "/usr/local/src/powa-web-dev/powa/framework.py", line 64, in execute
    query = resolve_nsps(query, self.connection)
  File "/usr/local/src/powa-web-dev/powa/framework.py", line 91, in resolve_nsps
    return query.format(**connection._nsps)
KeyError: 'hypopg'
```

Actually the flash message cannot be displayed since it's a `KeyError` not a `psycopg2.Error`.

Steps to reproduce:
 - run the `powa-dev-demo.yml` podman compose file,
 - drop the extension in obvious database:
   - `podman exec -it powa-dev-remote-primary bash`)
   - `su postgres`,
   - `psql -d obvious`
   - `DROP extension hypopg;`

**Comment by pgiraud** [comment]
Should be fixed via 6cb7b2d

**Comment by rjuju** [comment]
I don't think that this commit will fix the error you mentioned.  IIUC it's coming from the `self.execute()` in this snippet:

```py
        hypo_version = self.has_extension_version(
            srvid, "hypopg", "0.0.3", database=database
        )
        if indexes and hypo_version:
            # identify indexes
            # create them
            allindexes = [
                ind
                for indcollection in indexes.values()
                for ind in indcollection
            ]
            for ind in allindexes:
                (sql, params) = ind.hypo_ddl
                if sql is not None:
                    try:
                        ind.name = self.execute(
                            sql,
                            params=params,
                            srvid=srvid,
                            database=database,
                            remote_access=True,
                        )[0]["indexname"]
                    except Error as e:
                        self.flash(
                            "Could not create hypothetical index: %s" % str(e)
                        )
```

which should only be executed if the hypop extension does exist, so probably something else is going on.  The commit will only replace the `KeyError` stacktrace with an `Extension not found` one.
