### ISSUE TITLE
can't see graph

### ISSUE THREAD

**Issue by mkdel** [powa-team/powa-web#87]
Hi,

I'm totally newbie and can't handle what I faced.
Can't see any graph on my brand new POWA
![image](https://user-images.githubusercontent.com/55700023/65429230-839cfe80-de1e-11e9-8009-7b1544a1fbfe.png)

on running POWA-WEB console I can see:

[E 190923 16:27:10 web:1788] Uncaught exception GET /metrics/database_overview/postgres/?from=2019-09-23+15%3A27%3A10%2B0300&to=2019-09-23+16%3A27%3A10%2B0300 (YYY.YYY.YYY.YYY)
    HTTPServerRequest(protocol='http', host='XXX.XXX.XXX.XXX:8888', method='GET', uri='/metrics/database_overview/postgres/?from=2019-09-23+15%3A27%3A10%2B0300&to=2019-09-23+16%3A27%3A10%2B0300', version='HTTP/1.1', remote_ip='YYY.YYY.YYY.YYY')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/powa/dashboards.py", line 76, in get
        query = self.query
      File "/usr/local/lib/python3.6/dist-packages/powa/database.py", line 45, in query
        subquery = powa_getstatdata_sample("db")
      File "/usr/local/lib/python3.6/dist-packages/powa/sql/views.py", line 447, in powa_getstatdata_sample
        biggest("blk_write_time")]).select_from(base_query).apply_labels()
      File "<string>", line 2, in select
      File "<string>", line 2, in __init__
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/deprecations.py", line 128, in warned
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/selectable.py", line 2981, in __init__
        c = _interpret_as_column_or_from(c)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 4634, in _interpret_as_column_or_from
        _no_column_coercion(element)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 4545, in _no_column_coercion
        else "column",
    sqlalchemy.exc.ArgumentError: Textual column expression 'dbid' should be explicitly declared with text('dbid'), or use column('dbid') for more specificity
[E 190923 16:27:10 web:2246] 500 GET /metrics/database_overview/postgres/?from=2019-09-23+15%3A27%3A10%2B0300&to=2019-09-23+16%3A27%3A10%2B0300 (YYY.YYY.YYY.YYY) 49.66ms

What did I miss?

**Comment by rjuju** [comment]
Hello,

This is probably something fixed in https://github.com/powa-team/powa-web/commit/6fedf9d606349ecf42b7f020ea6abc70e535902f.  This will be available as part of powa4, which is still in beta.

If you want to stay on v3, the only workaround I'm aware of is to downgrade sqlalchemy to < 1.3.

**Comment by mkdel** [comment]
Thanks a lot! that's helped :)

**Comment by rjuju** [comment]
Great, thanks for confirming!
