### ISSUE TITLE
query error in powa v4-beta1

### ISSUE THREAD

**Issue by erichanson** [powa-team/powa-web#96]
Installed powa v4 beta1, getting this:
```
[E 200303 22:38:20 web:1495] Uncaught exception GET /metrics/database/restapi/wizard/?from=2020-03-03+15%3A38%3A17-0600&to=2020-03-03+16%3A38%3A17-0600 (10.0.31.59)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/metrics/database/restapi/wizard/?from=2020-03-03+15%3A38%3A17-0600&to=2020-03-03+16%3A38%3A17-0600', version='HTTP/1.1', remote_ip='10.0.31.59', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Sec-Fetch-Site': 'same-origin', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Sec-Fetch-Mode': 'cors', 'Referer': 'http://localhost:8888/database/restapi/overview/', 'Cookie': 'username="2|1:0|10:1582046468|8:username|8:cG93YQ==|4587b87aaab09e1423fc19d378bc82a3c97ea3fc1169aae8a8249d1256e1d48c"; password="2|1:0|10:1582046468|8:password|8:aGltb20=|7ccdf24c1f9394fc9fbdcc28516faab3ed140147ed9d1cb5254734fe672bcfc5"; server="2|1:0|10:1582046468|6:server|8:bWFpbg==|c2403441911ba3534203478f8e6ef1c23ce6c6c8a760c125b4a521c0c4e14dab"; _flashes="2|1:0|10:1583275096|8:_flashes|4:Ti4=|230a95b66521d560b9d7cdab4ecd976c2f04030383d613ad7b8f2a375e817e28"', 'Sec-Fetch-Dest': 'empty'})
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1412, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/lib/python2.7/site-packages/powa/dashboards.py", line 77, in get
        values = self.execute(query, params=url_params)
      File "/usr/lib/python2.7/site-packages/powa/framework.py", line 184, in execute
        return engine.execute(query, **params)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1751, in execute
        return connection.execute(statement, *multiparams, **params)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
        return meth(self, multiparams, params)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
        context)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
        exc_info
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
        context)
      File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
        cursor.execute(statement, parameters)
    ProgrammingError: (ProgrammingError) each UNION query must have the same number of columns
    LINE 13:     SELECT queryid, qualid, pqnc.ts, pqnc.occurences, pqnc.e...
                        ^
     "SELECT array_agg(queryid) AS queryids, qualid, CAST(quals AS JSONB) AS quals, occurences, execution_count, array_agg(query) AS queries, avg_filter, filter_ratio \nFROM (SELECT qualid, powa_statements.queryid AS queryid, query, powa_statements.dbid AS dbid, to_json(quals) AS quals, sum(execution_count) AS execution_count, sum(occurences) AS occurences, sum(nbfiltered) / sum(occurences) AS avg_filter, CASE WHEN (sum(execution_count) = %(sum_1)s) THEN %(param_1)s ELSE (sum(nbfiltered) / CAST(sum(execution_count) AS NUMERIC)) * %(param_2)s END AS filter_ratio \nFROM \n    (\n    SELECT queryid, qualid, (unnested.records).*\n    FROM (\n        SELECT pqnh.qualid, pqnh.queryid, pqnh.dbid, pqnh.userid, pqnh.coalesce_range, unnest(records) as records\n        FROM powa_qualstats_quals_history pqnh\n        WHERE coalesce_range  && tstzrange(%(from)s, %(to)s, '[]')\n    ) AS unnested\n    WHERE tstzrange(%(from)s, %(to)s, '[]') @> (records).ts\n    UNION ALL\n    SELECT queryid, qualid, pqnc.ts, pqnc.occurences, pqnc.execution_count, pqnc.nbfiltered\n    FROM powa_qualstats_quals_history_current pqnc\n    WHERE tstzrange(%(from)s, %(to)s, '[]') @> pqnc.ts\n    ) h\n    JOIN powa_qualstats_quals pqnh USING (queryid, qualid)\n     JOIN powa_statements ON powa_statements.queryid = pqnh.queryid GROUP BY qualid, powa_statements.queryid, powa_statements.dbid, powa_statements.query, quals) AS anon_1 JOIN powa_databases ON powa_databases.oid = dbid \nWHERE powa_databases.datname = %(database)s AND avg_filter > %(avg_filter_1)s AND filter_ratio > %(filter_ratio_1)s GROUP BY qualid, execution_count, occurences, CAST(quals AS JSONB), avg_filter, filter_ratio ORDER BY occurences DESC \n LIMIT %(param_3)s" {'from': u'2020-03-03 15:38:17-0600', 'database': u'restapi', 'filter_ratio_1': 0.3, 'param_1': 0, 'param_3': 200, 'param_2': 100, 'to': u'2020-03-03 16:38:17-0600', 'avg_filter_1': 1000, 'sum_1': 0}
```

My extensions look like this:

```
powa=# \dx
                                       List of installed extensions
        Name        |  Version   |   Schema   |                        Description
--------------------+------------+------------+-----------------------------------------------------------
 btree_gist         | 1.5        | public     | support for indexing common datatypes in GiST
 pg_qualstats       | 1.0.9      | public     | An extension collecting statistics about quals
 pg_stat_kcache     | 2.1.1      | public     | Kernel statistics gathering
 pg_stat_statements | 1.6        | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0        | pg_catalog | PL/pgSQL procedural language
 powa               | 4.0.0beta1 | public     | PostgreSQL Workload Analyser-core
(6 rows)
```

**Comment by rjuju** [comment]
Hi,

Thanks for the report!  Did you install the 4.0.0beta1 version or a later commit? I can see a bug using current head due to changes in pg_qualstats, but it was introduced after the beta1.

Just to be sure, can you show the output of `\d powa_qualstats_history_item `?

On the 4.0.0beta1 tag, it should be

```
             Composite type "public.powa_qualstats_history_item"
     Column      |           Type           | Collation | Nullable | Default 
-----------------+--------------------------+-----------+----------+---------
 ts              | timestamp with time zone |           |          | 
 occurences      | bigint                   |           |          | 
 execution_count | bigint                   |           |          | 
 nbfiltered      | bigint                   |           |          | 
```

**Comment by erichanson** [comment]
Yes, I actually installed from HEAD.  I thought the latest release I could find was 3.2 but now I can't find where I was looking and see there's a 4.0 beta release.  I can either just switch to the release, or, which version of pg_qualstats should I be using with HEAD?  Thanks for the cool project!

**Comment by erichanson** [comment]
I will post the structure of `powa_qualstats_history_item` tomorrow when I am at work.

**Comment by rjuju** [comment]
Thanks!

The latest stable release is powa-web 3.2.1 (which supports recent versions of SQLAlchemy).  v4 shoudn't be far from release, but given the amount of changes a lot of testing is required, as you can see :)

For pg_qualstats, the version 2.0.0 had many enhancements, and isn't released yet.  powa-archivist  HEAD should handle both 1.X and 2.X versions, so you should be able to use any of the.  But you just find out that I missed to update powa-web accordingly.  I just fixed it in https://github.com/powa-team/powa-web/commit/78ee392d50f3eb6a302ab04ce0ca926c30785e17, and while testing found an unrelated issue in powa-archivist, for which I also pushed a fix.  Updating powa-web should be enough, but for powa-archivist you'd need to drop/create the extension, or apply the diff manually (update powa_servers rows and update powa_qualstats_register()).

Thanks again for the report!

**Comment by erichanson** [comment]
Ok thank you!

BTW:
```
powa=# \d powa_qualstats_history_item
                 Composite type "public.powa_qualstats_history_item"
         Column          |           Type           | Collation | Nullable | Default
-------------------------+--------------------------+-----------+----------+---------
 ts                      | timestamp with time zone |           |          |
 occurences              | bigint                   |           |          |
 execution_count         | bigint                   |           |          |
 nbfiltered              | bigint                   |           |          |
 mean_err_estimate_ratio | double precision         |           |          |
 mean_err_estimate_num   | double precision         |           |          |
```

**Comment by erichanson** [comment]
Ok making some progress!  Now the app runs but I'm also getting a red bar across the top of the screen, with this error:

```
<local>: powa_take_snapshot(0): function "powa_qualstats_snapshot" failed: column qs.mean_err_estimate_ratio does not exist
```

Can I just install pg_qualstats 2.0 from source?  Or maybe powa should require a particular version of pg_qualstats?

**Comment by rjuju** [comment]
Ah that's strange, it should be supported.  Are you using a local snapshot or a remote snapshot?

Can you check that the version of powa-archivist on the server you're monitoring does have this version of the function: https://github.com/powa-team/powa-archivist/blob/master/powa--4.0.0beta1.sql#L3340

**Comment by erichanson** [comment]
```
powa=# \df powa_qualstats_src
List of functions
-[ RECORD 1 ]-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Schema              | public
Name                | powa_qualstats_src
Result data type    | SETOF record
Argument data types | _srvid integer, OUT ts timestamp with time zone, OUT uniquequalnodeid bigint, OUT dbid oid, OUT userid oid, OUT qualnodeid bigint, OUT occurences bigint, OUT execution_count bigint, OUT nbfiltered bigint, OUT mean_err_estimate_ratio double precision, OUT mean_err_estimate_num double precision, OUT queryid bigint, OUT constvalues character varying[], OUT quals qual_type[]
Type                | func

powa=# \x
Expanded display is off.
powa=# \dx
                                       List of installed extensions
        Name        |  Version   |   Schema   |                        Description
--------------------+------------+------------+-----------------------------------------------------------
 btree_gist         | 1.5        | public     | support for indexing common datatypes in GiST
 pg_qualstats       | 1.0.9      | public     | An extension collecting statistics about quals
 pg_stat_kcache     | 2.1.1      | public     | Kernel statistics gathering
 pg_stat_statements | 1.6        | public     | track execution statistics of all SQL statements executed
 pg_wait_sampling   | 1.1        | public     | sampling based statistics of wait events
 plpgsql            | 1.0        | pg_catalog | PL/pgSQL procedural language
 powa               | 4.0.0beta1 | public     | PostgreSQL Workload Analyser-core
(7 rows)

powa=#
```

**Comment by erichanson** [comment]
I am running powa and the database I'm analyzing all on the same machine.

**Comment by rjuju** [comment]
On the main postgres instance you mean?

I'd need the source of the function actually stored, you can get it with either `\ef powa_qualstats_src` or `SELECT prosrc FROM pg_proc WHERE proname = 'powa_qualstats_src'` on the powa database.

**Comment by erichanson** [comment]
```
CREATE OR REPLACE FUNCTION public.powa_qualstats_src(_srvid integer, OUT ts timestamp with time zone, OUT uniquequalnodeid bigint, OUT dbid oid, OUT userid oid, OUT qualnodeid bigint, OUT occurences bigint, OUT execution_count bigint, OUT nbfiltered bigint, OUT mean_err_estimate_ratio double precision, OUT mean_err_estimate_num double precision, OUT queryid bigint, OUT constvalues character varying[], OUT quals qual_type[])
 RETURNS SETOF record
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  is_v2 bool;
BEGIN
    IF (_srvid = 0) THEN
        SELECT substr(extversion, 1, 1)::int >=2 INTO STRICT is_v2
          FROM pg_extension
          WHERE extname = 'pg_qualstats';

        RETURN QUERY
            SELECT now(), pgqs.uniquequalnodeid, pgqs.dbid, pgqs.userid,
                pgqs.qualnodeid, pgqs.occurences, pgqs.execution_count,
                pgqs.nbfiltered, pgqs.mean_err_estimate_ratio,
                pgqs.mean_err_estimate_num, pgqs.queryid, pgqs.constvalues,
                pgqs.quals
            FROM (
                SELECT coalesce(i.uniquequalid, i.uniquequalnodeid) AS uniquequalnodeid,
                    i.dbid, i.userid,  coalesce(i.qualid, i.qualnodeid) AS qualnodeid,
                    i.occurences, i.execution_count, i.nbfiltered,
                    i.mean_err_estimate_ratio, i.mean_err_estimate_num,
                    i.queryid,
                    array_agg(i.constvalue order by i.constant_position) AS constvalues,
                    array_agg(ROW(i.relid, i.attnum, i.opno, i.eval_type)::qual_type) AS quals
                FROM
                (
                    SELECT qs.dbid,
                    CASE WHEN lrelid IS NOT NULL THEN lrelid
                        WHEN rrelid IS NOT NULL THEN rrelid
                    END as relid,
                    qs.userid as userid,
                    CASE WHEN lrelid IS NOT NULL THEN lattnum
                        WHEN rrelid IS NOT NULL THEN rattnum
                    END as attnum,
                    qs.opno as opno,
                    qs.qualid as qualid,
                    qs.uniquequalid as uniquequalid,
                    qs.qualnodeid as qualnodeid,
                    qs.uniquequalnodeid as uniquequalnodeid,
                    qs.occurences as occurences,
                    qs.execution_count as execution_count,
                    qs.queryid as queryid,
                    qs.constvalue as constvalue,
                    qs.nbfiltered as nbfiltered,
                    CASE WHEN is_v2 THEN qs.mean_err_estimate_ratio
                      ELSE NULL
                    END AS mean_err_estimate_ratio,
                    CASE WHEN is_v2 THEN qs.mean_err_estimate_num
                      ELSE NULL
                    END AS mean_err_estimate_num,
                    qs.eval_type,
                    qs.constant_position
                    FROM pg_qualstats() qs
                    WHERE (qs.lrelid IS NULL) != (qs.rrelid IS NULL)
                ) i
                GROUP BY coalesce(i.uniquequalid, i.uniquequalnodeid),
                    coalesce(i.qualid, i.qualnodeid), i.dbid, i.userid,
                    i.occurences, i.execution_count, i.nbfiltered,
                    i.mean_err_estimate_ratio, i.mean_err_estimate_num,
                    i.queryid
            ) pgqs
            JOIN (
                -- if we use remote capture, powa_statements won't be
                -- populated, so we have to to retrieve the content of both
                -- statements sources.  Since there can (and probably) be
                -- duplicates, we use a UNION on purpose
                SELECT s1.queryid, s1.dbid, s1.userid
                    FROM pg_stat_statements s1
                UNION
                SELECT s2.queryid, s2.dbid, s2.userid
                    FROM powa_statements s2 WHERE s2.srvid = 0
            ) s USING(queryid, dbid, userid)
        -- we don't gather quals for databases that have been dropped
        JOIN pg_database d ON d.oid = s.dbid
        JOIN pg_roles r ON s.userid = r.oid
          AND NOT (r.rolname = ANY (string_to_array(
                    coalesce(current_setting('powa.ignored_users'), ''),
                    ',')))
        WHERE pgqs.dbid NOT IN (SELECT oid FROM powa_databases WHERE dropped IS NOT NULL);
    ELSE
        RETURN QUERY
            SELECT pgqs.ts, pgqs.uniquequalnodeid, pgqs.dbid, pgqs.userid,
                pgqs.qualnodeid, pgqs.occurences, pgqs.execution_count,
                pgqs.nbfiltered, pgqs.mean_err_estimate_ratio,
                pgqs.mean_err_estimate_num, pgqs.queryid, pgqs.constvalues,
                pgqs.quals
            FROM powa_qualstats_src_tmp pgqs
        WHERE pgqs.srvid = _srvid;
    END IF;
END;
$function$
```

**Comment by erichanson** [comment]
FWIW, I upgraded to the HEAD version of `pg_qualstats` and the problem went away.  Now I have a new problem in that the other database on the local PostgreSQL instance besides `powa` (the one I am trying to analyze) is not showing up.  Should I file a different issue for that?  I'm excited to use v4.0 but if it is too soon to test I can go back to 3.2.

**Comment by erichanson** [comment]
Nevermind, my database eventually showed up (or I was looking in the wrong spot).

And now I'm back to running into issue #95 again aaarg.  Switching over to that one.  But I am happy to roll back to `pg_qualstats` v1.0.9 to help debug this issue if need be.

**Comment by rjuju** [comment]
Yes, I just realized that the way I handled pg_qualstats < 2 was pretty dumb and definitely can't work, I should have tested it.

That issue should be fixed with https://github.com/powa-team/powa-archivist/commit/bd864c2c4c22a6a550a119d7664b4cda0e23c898.  You can either do a full `make install / drop extension powa / create extension powa` cycle, or just copy/paste the new CREATE OR REPLACE powa_qualstats_src order.  This time I tested with both pg_qualstats 2.0.0 and 1.0.9.

**Comment by erichanson** [comment]
Great!  I upgraded to 2.0.0 so if you tested I won't. :). Thank you!!

**Comment by SonicGD** [comment]
@rjuju hello, can you please push new powateam/powa-web-git docker image with https://github.com/powa-team/powa-web/commit/78ee392d50f3eb6a302ab04ce0ca926c30785e17 fix? Thx.

**Comment by rjuju** [comment]
Thanks for the reminder @SonicGD, I just pushed a new image!

**Comment by SonicGD** [comment]
Thanks!
